-- CGE NJ Live Database Backup
-- Generated: 2026-04-30T22:45:30.261Z
-- Host: helium / heliumdb (shared dev+prod database)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;

-- ── SEQUENCES ────────────────────────────────────────────────────────────

CREATE SEQUENCE IF NOT EXISTS admin_users_id_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS posts_id_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS comments_id_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS events_id_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS link_clicks_id_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS newsletter_subscribers_id_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS post_versions_id_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS post_views_id_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS promotion_bookings_id_seq START WITH 1 INCREMENT BY 1;

-- ── TABLES ──────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS admin_users (
  id INTEGER NOT NULL PRIMARY KEY DEFAULT nextval('admin_users_id_seq'),
  email TEXT NOT NULL UNIQUE,
  password_hash TEXT,
  role TEXT NOT NULL DEFAULT 'editor',
  invite_token TEXT,
  invite_accepted BOOLEAN DEFAULT 'false',
  is_active BOOLEAN DEFAULT 'true',
  created_at TIMESTAMP DEFAULT 'now()'
);

CREATE TABLE IF NOT EXISTS posts (
  id INTEGER NOT NULL PRIMARY KEY DEFAULT nextval('posts_id_seq'),
  title TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  excerpt TEXT,
  content TEXT,
  cover_image_url TEXT,
  is_published BOOLEAN DEFAULT 'false',
  is_gated BOOLEAN DEFAULT 'false',
  published_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT 'now()',
  updated_at TIMESTAMP DEFAULT 'now()'
);

CREATE TABLE IF NOT EXISTS comments (
  id INTEGER NOT NULL PRIMARY KEY DEFAULT nextval('comments_id_seq'),
  post_id INTEGER NOT NULL REFERENCES posts(id),
  parent_id INTEGER REFERENCES comments(id),
  email TEXT NOT NULL,
  body TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT 'now()'
);

CREATE TABLE IF NOT EXISTS events (
  id INTEGER NOT NULL PRIMARY KEY DEFAULT nextval('events_id_seq'),
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  date TEXT NOT NULL,
  region TEXT NOT NULL,
  image_url TEXT NOT NULL,
  ticket_link TEXT,
  created_at TIMESTAMP DEFAULT 'now()',
  city TEXT,
  event_time TEXT,
  venue TEXT,
  organizer TEXT,
  influencer TEXT,
  genre TEXT,
  instagram_handle TEXT
);

CREATE TABLE IF NOT EXISTS link_clicks (
  id INTEGER NOT NULL PRIMARY KEY DEFAULT nextval('link_clicks_id_seq'),
  post_id INTEGER REFERENCES posts(id),
  url TEXT NOT NULL,
  clicked_at TIMESTAMP DEFAULT 'now()',
  source_page TEXT
);

CREATE TABLE IF NOT EXISTS newsletter_subscribers (
  id INTEGER NOT NULL PRIMARY KEY DEFAULT nextval('newsletter_subscribers_id_seq'),
  name TEXT NOT NULL DEFAULT ,
  email TEXT NOT NULL UNIQUE,
  region TEXT,
  created_at TIMESTAMP DEFAULT 'now()',
  referrer TEXT,
  has_access BOOLEAN DEFAULT 'true'
);

CREATE TABLE IF NOT EXISTS post_versions (
  id INTEGER NOT NULL PRIMARY KEY DEFAULT nextval('post_versions_id_seq'),
  post_id INTEGER REFERENCES posts(id),
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  saved_at TIMESTAMP DEFAULT 'now()',
  saved_by INTEGER REFERENCES admin_users(id)
);

CREATE TABLE IF NOT EXISTS post_views (
  id INTEGER NOT NULL PRIMARY KEY DEFAULT nextval('post_views_id_seq'),
  post_id INTEGER REFERENCES posts(id),
  viewed_at TIMESTAMP DEFAULT 'now()'
);

CREATE TABLE IF NOT EXISTS promotion_bookings (
  id INTEGER NOT NULL PRIMARY KEY DEFAULT nextval('promotion_bookings_id_seq'),
  venue_name TEXT NOT NULL,
  contact_name TEXT,
  phone TEXT,
  email TEXT NOT NULL,
  event_date TEXT NOT NULL,
  region TEXT NOT NULL,
  event_type TEXT NOT NULL,
  budget_range TEXT,
  instagram_handle TEXT,
  ready_to_move_forward TEXT,
  created_at TIMESTAMP DEFAULT 'now()',
  mode TEXT,
  event_name TEXT,
  event_time TEXT,
  city TEXT,
  event_type_other TEXT,
  status TEXT DEFAULT 'New',
  admin_notes TEXT
);

-- ── DATA ────────────────────────────────────────────────────────────────

-- Table: admin_users (2 rows)
INSERT INTO admin_users (id, email, password_hash, role, invite_token, invite_accepted, is_active, created_at) VALUES (1, 'centralgroupevents@gmail.com', '$2b$12$lYHg9FML2p7cux8UtJz/B.WeYKtsYMNeIKERmYPbq1V3b0OoVR4eO', 'superadmin', NULL, true, true, '2026-03-18T19:15:07.357Z');
INSERT INTO admin_users (id, email, password_hash, role, invite_token, invite_accepted, is_active, created_at) VALUES (2, 'editor@test.com', '$2b$12$9A.EI/oIu5YTQUxUAbH.Xeeva4hRbTKNJpKNnpV8x7cthFCP9eD66', 'editor', NULL, true, false, '2026-03-18T19:25:31.831Z');

-- Table: posts (4 rows)
INSERT INTO posts (id, title, slug, excerpt, content, cover_image_url, is_published, is_gated, published_at, created_at, updated_at) VALUES (1, 'Updated Test Post', 'updated-test-post', 'This is a test', 'Updated content', NULL, false, false, NULL, '2026-03-18T19:15:39.766Z', '2026-03-18T19:32:17.825Z');
INSERT INTO posts (id, title, slug, excerpt, content, cover_image_url, is_published, is_gated, published_at, created_at, updated_at) VALUES (2, 'Gated Post', 'gated-post', NULL, 'SECRET CONTENT', NULL, true, true, '2026-03-18T19:32:16.712Z', '2026-03-18T19:32:16.561Z', '2026-03-18T19:32:16.712Z');
INSERT INTO posts (id, title, slug, excerpt, content, cover_image_url, is_published, is_gated, published_at, created_at, updated_at) VALUES (3, 'Test Blog Post', 'test-blog-post', '', '', '', false, false, NULL, '2026-03-18T20:03:58.585Z', '2026-03-18T20:03:58.585Z');
INSERT INTO posts (id, title, slug, excerpt, content, cover_image_url, is_published, is_gated, published_at, created_at, updated_at) VALUES (4, 'Test Table Post', 'test-table-post', '', '', '', false, false, NULL, '2026-03-18T20:10:30.996Z', '2026-03-18T20:10:30.996Z');

-- Table: comments (1 rows)
INSERT INTO comments (id, post_id, parent_id, email, body, created_at) VALUES (1, 1, NULL, 'commenter@example.com', 'Great post!', '2026-03-18T19:21:17.569Z');

-- Table: events (202 rows)
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (5, 'COUNTRY LINE DANCING', 'Live event in Asbury Park, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-03-09T20:50:12.848Z', 'Asbury Park', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (6, 'AYA FRIDAYS', 'Live event in Edison, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-03-09T20:50:12.852Z', 'Edison', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (7, 'FRIDAY NIGHT OUT', 'Live event in Plainfield, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-03-09T20:50:12.856Z', 'Plainfield', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (8, 'UNDERGROUND FRIDAYS WITH DJ FIORELLA', 'Live event in Somerville, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-03-09T20:50:12.859Z', 'Somerville', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (9, '90s vs 2000s BASH', 'Live event in East Brunswick, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-03-09T20:50:12.862Z', 'East Brunswick', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (10, 'SAK PASE AFRO - GHANA INDEPENDENCE DAY', 'Live event in Roselle, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-03-09T20:50:12.865Z', 'Roselle', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (11, 'THE BIGGIE BRUNCH', 'Live event in Clifton, NJ', '2026-03-06', 'North NJ', '', '#', '2026-03-09T20:50:12.868Z', 'Clifton', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (12, 'JOJOS HAPPY HOUR', 'Live event in Garfield, NJ', '2026-03-06', 'North NJ', '', '#', '2026-03-09T20:50:12.871Z', 'Garfield', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (13, 'COMMUNITY NIGHT: JOURNEYS HOME BY MOONLIGHT', 'Live event in Newark, NJ', '2026-03-06', 'North NJ', '', '#', '2026-03-09T20:50:12.875Z', 'Newark', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (14, 'JAZZY FRIDAYS', 'Live event in Fort Lee, NJ', '2026-03-06', 'North NJ', '', '#', '2026-03-09T20:50:12.878Z', 'Fort Lee', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (15, 'DREAM: A LISTENING & VISUAL EXPERIENCE', 'Live event in Jersey City, NJ', '2026-03-06', 'North NJ', '', '#', '2026-03-09T20:50:12.881Z', 'Jersey City', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (39, 'Summer Vibes Day Party', 'The hottest day party in Central NJ with live DJs and drinks.', '2026-07-15', 'Central NJ', 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', 'https://example.com/tickets', '2026-04-29T21:01:37.434Z', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (40, 'Midnight R&B Lounge', 'Smooth R&B hits all night long.', '2026-07-22', 'North NJ', 'https://images.unsplash.com/photo-1470229722913-7c090be5f5ae?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', 'https://example.com/tickets', '2026-04-29T21:01:37.467Z', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (41, 'Beachfront Bash', 'Exclusive beachfront party to start the weekend right.', '2026-07-29', 'South NJ', 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', 'https://example.com/tickets', '2026-04-29T21:01:37.479Z', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (42, 'Techno Warehouse', 'Underground techno from 10PM to late.', '2026-08-05', 'North NJ', 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', 'https://example.com/tickets', '2026-04-29T21:01:37.482Z', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (43, 'COUNTRY LINE DANCING', 'Live event in Asbury Park, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-29T21:01:37.487Z', 'Asbury Park', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (44, 'AYA FRIDAYS', 'Live event in Edison, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-29T21:01:37.491Z', 'Edison', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (45, 'FRIDAY NIGHT OUT', 'Live event in Plainfield, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-29T21:01:37.494Z', 'Plainfield', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (46, 'UNDERGROUND FRIDAYS WITH DJ FIORELLA', 'Live event in Somerville, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-29T21:01:37.497Z', 'Somerville', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (47, '90s vs 2000s BASH', 'Live event in East Brunswick, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-29T21:01:37.501Z', 'East Brunswick', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (48, 'SAK PASE AFRO - GHANA INDEPENDENCE DAY', 'Live event in Roselle, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-29T21:01:37.512Z', 'Roselle', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (49, 'THE BIGGIE BRUNCH', 'Live event in Clifton, NJ', '2026-03-06', 'North NJ', '', '#', '2026-04-29T21:01:37.516Z', 'Clifton', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (50, 'JOJOS HAPPY HOUR', 'Live event in Garfield, NJ', '2026-03-06', 'North NJ', '', '#', '2026-04-29T21:01:37.519Z', 'Garfield', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (51, 'COMMUNITY NIGHT: JOURNEYS HOME BY MOONLIGHT', 'Live event in Newark, NJ', '2026-03-06', 'North NJ', '', '#', '2026-04-29T21:01:37.522Z', 'Newark', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (52, 'JAZZY FRIDAYS', 'Live event in Fort Lee, NJ', '2026-03-06', 'North NJ', '', '#', '2026-04-29T21:01:37.525Z', 'Fort Lee', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (53, 'DREAM: A LISTENING & VISUAL EXPERIENCE', 'Live event in Jersey City, NJ', '2026-03-06', 'North NJ', '', '#', '2026-04-29T21:01:37.528Z', 'Jersey City', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (54, 'COUNTRY LINE DANCING', 'Live event in Asbury Park, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-29T21:02:26.136Z', 'Asbury Park', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (55, 'AYA FRIDAYS', 'Live event in Edison, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-29T21:02:26.172Z', 'Edison', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (56, 'FRIDAY NIGHT OUT', 'Live event in Plainfield, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-29T21:02:26.177Z', 'Plainfield', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (57, 'UNDERGROUND FRIDAYS WITH DJ FIORELLA', 'Live event in Somerville, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-29T21:02:26.192Z', 'Somerville', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (58, '90s vs 2000s BASH', 'Live event in East Brunswick, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-29T21:02:26.195Z', 'East Brunswick', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (59, 'SAK PASE AFRO - GHANA INDEPENDENCE DAY', 'Live event in Roselle, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-29T21:02:26.199Z', 'Roselle', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (60, 'THE BIGGIE BRUNCH', 'Live event in Clifton, NJ', '2026-03-06', 'North NJ', '', '#', '2026-04-29T21:02:26.203Z', 'Clifton', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (61, 'JOJOS HAPPY HOUR', 'Live event in Garfield, NJ', '2026-03-06', 'North NJ', '', '#', '2026-04-29T21:02:26.207Z', 'Garfield', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (62, 'COMMUNITY NIGHT: JOURNEYS HOME BY MOONLIGHT', 'Live event in Newark, NJ', '2026-03-06', 'North NJ', '', '#', '2026-04-29T21:02:26.210Z', 'Newark', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (63, 'JAZZY FRIDAYS', 'Live event in Fort Lee, NJ', '2026-03-06', 'North NJ', '', '#', '2026-04-29T21:02:26.214Z', 'Fort Lee', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (64, 'DREAM: A LISTENING & VISUAL EXPERIENCE', 'Live event in Jersey City, NJ', '2026-03-06', 'North NJ', '', '#', '2026-04-29T21:02:26.228Z', 'Jersey City', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (65, 'COUNTRY LINE DANCING', 'Live event in Asbury Park, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-29T21:03:59.309Z', 'Asbury Park', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (66, 'AYA FRIDAYS', 'Live event in Edison, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-29T21:03:59.340Z', 'Edison', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (67, 'FRIDAY NIGHT OUT', 'Live event in Plainfield, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-29T21:03:59.344Z', 'Plainfield', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (68, 'UNDERGROUND FRIDAYS WITH DJ FIORELLA', 'Live event in Somerville, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-29T21:03:59.358Z', 'Somerville', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (69, '90s vs 2000s BASH', 'Live event in East Brunswick, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-29T21:03:59.364Z', 'East Brunswick', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (70, 'SAK PASE AFRO - GHANA INDEPENDENCE DAY', 'Live event in Roselle, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-29T21:03:59.371Z', 'Roselle', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (71, 'THE BIGGIE BRUNCH', 'Live event in Clifton, NJ', '2026-03-06', 'North NJ', '', '#', '2026-04-29T21:03:59.374Z', 'Clifton', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (72, 'JOJOS HAPPY HOUR', 'Live event in Garfield, NJ', '2026-03-06', 'North NJ', '', '#', '2026-04-29T21:03:59.378Z', 'Garfield', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (73, 'COMMUNITY NIGHT: JOURNEYS HOME BY MOONLIGHT', 'Live event in Newark, NJ', '2026-03-06', 'North NJ', '', '#', '2026-04-29T21:03:59.381Z', 'Newark', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (74, 'JAZZY FRIDAYS', 'Live event in Fort Lee, NJ', '2026-03-06', 'North NJ', '', '#', '2026-04-29T21:03:59.401Z', 'Fort Lee', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (75, 'DREAM: A LISTENING & VISUAL EXPERIENCE', 'Live event in Jersey City, NJ', '2026-03-06', 'North NJ', '', '#', '2026-04-29T21:03:59.405Z', 'Jersey City', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (76, 'COUNTRY LINE DANCING', 'Live event in Asbury Park, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-29T21:06:08.822Z', 'Asbury Park', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (77, 'AYA FRIDAYS', 'Live event in Edison, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-29T21:06:08.858Z', 'Edison', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (78, 'FRIDAY NIGHT OUT', 'Live event in Plainfield, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-29T21:06:08.872Z', 'Plainfield', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (79, 'UNDERGROUND FRIDAYS WITH DJ FIORELLA', 'Live event in Somerville, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-29T21:06:08.875Z', 'Somerville', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (80, '90s vs 2000s BASH', 'Live event in East Brunswick, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-29T21:06:08.880Z', 'East Brunswick', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (81, 'SAK PASE AFRO - GHANA INDEPENDENCE DAY', 'Live event in Roselle, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-29T21:06:08.884Z', 'Roselle', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (82, 'THE BIGGIE BRUNCH', 'Live event in Clifton, NJ', '2026-03-06', 'North NJ', '', '#', '2026-04-29T21:06:08.888Z', 'Clifton', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (83, 'JOJOS HAPPY HOUR', 'Live event in Garfield, NJ', '2026-03-06', 'North NJ', '', '#', '2026-04-29T21:06:08.893Z', 'Garfield', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (84, 'COMMUNITY NIGHT: JOURNEYS HOME BY MOONLIGHT', 'Live event in Newark, NJ', '2026-03-06', 'North NJ', '', '#', '2026-04-29T21:06:08.909Z', 'Newark', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (85, 'JAZZY FRIDAYS', 'Live event in Fort Lee, NJ', '2026-03-06', 'North NJ', '', '#', '2026-04-29T21:06:08.913Z', 'Fort Lee', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (86, 'DREAM: A LISTENING & VISUAL EXPERIENCE', 'Live event in Jersey City, NJ', '2026-03-06', 'North NJ', '', '#', '2026-04-29T21:06:08.917Z', 'Jersey City', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (87, 'COUNTRY LINE DANCING', 'Live event in Asbury Park, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-29T21:10:56.525Z', 'Asbury Park', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (88, 'AYA FRIDAYS', 'Live event in Edison, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-29T21:10:56.529Z', 'Edison', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (89, 'FRIDAY NIGHT OUT', 'Live event in Plainfield, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-29T21:10:56.537Z', 'Plainfield', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (90, 'UNDERGROUND FRIDAYS WITH DJ FIORELLA', 'Live event in Somerville, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-29T21:10:56.548Z', 'Somerville', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (91, '90s vs 2000s BASH', 'Live event in East Brunswick, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-29T21:10:56.551Z', 'East Brunswick', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (92, 'SAK PASE AFRO - GHANA INDEPENDENCE DAY', 'Live event in Roselle, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-29T21:10:56.555Z', 'Roselle', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (93, 'THE BIGGIE BRUNCH', 'Live event in Clifton, NJ', '2026-03-06', 'North NJ', '', '#', '2026-04-29T21:10:56.559Z', 'Clifton', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (94, 'JOJOS HAPPY HOUR', 'Live event in Garfield, NJ', '2026-03-06', 'North NJ', '', '#', '2026-04-29T21:10:56.562Z', 'Garfield', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (95, 'COMMUNITY NIGHT: JOURNEYS HOME BY MOONLIGHT', 'Live event in Newark, NJ', '2026-03-06', 'North NJ', '', '#', '2026-04-29T21:10:56.566Z', 'Newark', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (96, 'JAZZY FRIDAYS', 'Live event in Fort Lee, NJ', '2026-03-06', 'North NJ', '', '#', '2026-04-29T21:10:56.569Z', 'Fort Lee', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (97, 'DREAM: A LISTENING & VISUAL EXPERIENCE', 'Live event in Jersey City, NJ', '2026-03-06', 'North NJ', '', '#', '2026-04-29T21:10:56.573Z', 'Jersey City', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (98, 'COUNTRY LINE DANCING', 'Live event in Asbury Park, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-29T21:11:23.071Z', 'Asbury Park', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (99, 'AYA FRIDAYS', 'Live event in Edison, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-29T21:11:23.107Z', 'Edison', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (100, 'FRIDAY NIGHT OUT', 'Live event in Plainfield, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-29T21:11:23.122Z', 'Plainfield', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (101, 'UNDERGROUND FRIDAYS WITH DJ FIORELLA', 'Live event in Somerville, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-29T21:11:23.127Z', 'Somerville', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (102, '90s vs 2000s BASH', 'Live event in East Brunswick, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-29T21:11:23.131Z', 'East Brunswick', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (103, 'SAK PASE AFRO - GHANA INDEPENDENCE DAY', 'Live event in Roselle, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-29T21:11:23.141Z', 'Roselle', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (104, 'THE BIGGIE BRUNCH', 'Live event in Clifton, NJ', '2026-03-06', 'North NJ', '', '#', '2026-04-29T21:11:23.144Z', 'Clifton', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (105, 'JOJOS HAPPY HOUR', 'Live event in Garfield, NJ', '2026-03-06', 'North NJ', '', '#', '2026-04-29T21:11:23.149Z', 'Garfield', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (106, 'COMMUNITY NIGHT: JOURNEYS HOME BY MOONLIGHT', 'Live event in Newark, NJ', '2026-03-06', 'North NJ', '', '#', '2026-04-29T21:11:23.163Z', 'Newark', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (107, 'JAZZY FRIDAYS', 'Live event in Fort Lee, NJ', '2026-03-06', 'North NJ', '', '#', '2026-04-29T21:11:23.166Z', 'Fort Lee', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (108, 'DREAM: A LISTENING & VISUAL EXPERIENCE', 'Live event in Jersey City, NJ', '2026-03-06', 'North NJ', '', '#', '2026-04-29T21:11:23.169Z', 'Jersey City', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (109, 'COUNTRY LINE DANCING', 'Live event in Asbury Park, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-29T21:12:05.839Z', 'Asbury Park', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (110, 'AYA FRIDAYS', 'Live event in Edison, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-29T21:12:05.843Z', 'Edison', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (111, 'FRIDAY NIGHT OUT', 'Live event in Plainfield, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-29T21:12:05.847Z', 'Plainfield', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (112, 'UNDERGROUND FRIDAYS WITH DJ FIORELLA', 'Live event in Somerville, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-29T21:12:05.852Z', 'Somerville', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (113, '90s vs 2000s BASH', 'Live event in East Brunswick, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-29T21:12:05.857Z', 'East Brunswick', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (114, 'SAK PASE AFRO - GHANA INDEPENDENCE DAY', 'Live event in Roselle, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-29T21:12:05.860Z', 'Roselle', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (115, 'THE BIGGIE BRUNCH', 'Live event in Clifton, NJ', '2026-03-06', 'North NJ', '', '#', '2026-04-29T21:12:05.863Z', 'Clifton', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (116, 'JOJOS HAPPY HOUR', 'Live event in Garfield, NJ', '2026-03-06', 'North NJ', '', '#', '2026-04-29T21:12:05.867Z', 'Garfield', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (117, 'COMMUNITY NIGHT: JOURNEYS HOME BY MOONLIGHT', 'Live event in Newark, NJ', '2026-03-06', 'North NJ', '', '#', '2026-04-29T21:12:05.869Z', 'Newark', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (118, 'JAZZY FRIDAYS', 'Live event in Fort Lee, NJ', '2026-03-06', 'North NJ', '', '#', '2026-04-29T21:12:05.873Z', 'Fort Lee', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (119, 'DREAM: A LISTENING & VISUAL EXPERIENCE', 'Live event in Jersey City, NJ', '2026-03-06', 'North NJ', '', '#', '2026-04-29T21:12:05.875Z', 'Jersey City', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (120, 'COUNTRY LINE DANCING', 'Live event in Asbury Park, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-29T21:15:09.616Z', 'Asbury Park', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (121, 'AYA FRIDAYS', 'Live event in Edison, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-29T21:15:09.621Z', 'Edison', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (122, 'FRIDAY NIGHT OUT', 'Live event in Plainfield, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-29T21:15:09.624Z', 'Plainfield', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (123, 'UNDERGROUND FRIDAYS WITH DJ FIORELLA', 'Live event in Somerville, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-29T21:15:09.628Z', 'Somerville', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (124, '90s vs 2000s BASH', 'Live event in East Brunswick, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-29T21:15:09.631Z', 'East Brunswick', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (125, 'SAK PASE AFRO - GHANA INDEPENDENCE DAY', 'Live event in Roselle, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-29T21:15:09.634Z', 'Roselle', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (126, 'THE BIGGIE BRUNCH', 'Live event in Clifton, NJ', '2026-03-06', 'North NJ', '', '#', '2026-04-29T21:15:09.637Z', 'Clifton', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (127, 'JOJOS HAPPY HOUR', 'Live event in Garfield, NJ', '2026-03-06', 'North NJ', '', '#', '2026-04-29T21:15:09.641Z', 'Garfield', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (128, 'COMMUNITY NIGHT: JOURNEYS HOME BY MOONLIGHT', 'Live event in Newark, NJ', '2026-03-06', 'North NJ', '', '#', '2026-04-29T21:15:09.644Z', 'Newark', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (129, 'JAZZY FRIDAYS', 'Live event in Fort Lee, NJ', '2026-03-06', 'North NJ', '', '#', '2026-04-29T21:15:09.646Z', 'Fort Lee', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (130, 'DREAM: A LISTENING & VISUAL EXPERIENCE', 'Live event in Jersey City, NJ', '2026-03-06', 'North NJ', '', '#', '2026-04-29T21:15:09.648Z', 'Jersey City', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (131, 'COUNTRY LINE DANCING', 'Live event in Asbury Park, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-29T21:16:04.952Z', 'Asbury Park', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (132, 'AYA FRIDAYS', 'Live event in Edison, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-29T21:16:04.956Z', 'Edison', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (133, 'FRIDAY NIGHT OUT', 'Live event in Plainfield, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-29T21:16:04.960Z', 'Plainfield', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (134, 'UNDERGROUND FRIDAYS WITH DJ FIORELLA', 'Live event in Somerville, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-29T21:16:04.962Z', 'Somerville', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (135, '90s vs 2000s BASH', 'Live event in East Brunswick, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-29T21:16:04.965Z', 'East Brunswick', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (136, 'SAK PASE AFRO - GHANA INDEPENDENCE DAY', 'Live event in Roselle, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-29T21:16:04.968Z', 'Roselle', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (137, 'THE BIGGIE BRUNCH', 'Live event in Clifton, NJ', '2026-03-06', 'North NJ', '', '#', '2026-04-29T21:16:04.972Z', 'Clifton', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (138, 'JOJOS HAPPY HOUR', 'Live event in Garfield, NJ', '2026-03-06', 'North NJ', '', '#', '2026-04-29T21:16:04.975Z', 'Garfield', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (139, 'COMMUNITY NIGHT: JOURNEYS HOME BY MOONLIGHT', 'Live event in Newark, NJ', '2026-03-06', 'North NJ', '', '#', '2026-04-29T21:16:04.978Z', 'Newark', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (140, 'JAZZY FRIDAYS', 'Live event in Fort Lee, NJ', '2026-03-06', 'North NJ', '', '#', '2026-04-29T21:16:04.980Z', 'Fort Lee', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (141, 'DREAM: A LISTENING & VISUAL EXPERIENCE', 'Live event in Jersey City, NJ', '2026-03-06', 'North NJ', '', '#', '2026-04-29T21:16:04.984Z', 'Jersey City', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (142, 'COUNTRY LINE DANCING', 'Live event in Asbury Park, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-29T21:18:11.035Z', 'Asbury Park', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (143, 'AYA FRIDAYS', 'Live event in Edison, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-29T21:18:11.069Z', 'Edison', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (144, 'FRIDAY NIGHT OUT', 'Live event in Plainfield, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-29T21:18:11.073Z', 'Plainfield', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (145, 'UNDERGROUND FRIDAYS WITH DJ FIORELLA', 'Live event in Somerville, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-29T21:18:11.077Z', 'Somerville', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (146, '90s vs 2000s BASH', 'Live event in East Brunswick, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-29T21:18:11.080Z', 'East Brunswick', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (147, 'SAK PASE AFRO - GHANA INDEPENDENCE DAY', 'Live event in Roselle, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-29T21:18:11.083Z', 'Roselle', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (148, 'THE BIGGIE BRUNCH', 'Live event in Clifton, NJ', '2026-03-06', 'North NJ', '', '#', '2026-04-29T21:18:11.087Z', 'Clifton', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (149, 'JOJOS HAPPY HOUR', 'Live event in Garfield, NJ', '2026-03-06', 'North NJ', '', '#', '2026-04-29T21:18:11.090Z', 'Garfield', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (150, 'COMMUNITY NIGHT: JOURNEYS HOME BY MOONLIGHT', 'Live event in Newark, NJ', '2026-03-06', 'North NJ', '', '#', '2026-04-29T21:18:11.095Z', 'Newark', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (151, 'JAZZY FRIDAYS', 'Live event in Fort Lee, NJ', '2026-03-06', 'North NJ', '', '#', '2026-04-29T21:18:11.099Z', 'Fort Lee', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (152, 'DREAM: A LISTENING & VISUAL EXPERIENCE', 'Live event in Jersey City, NJ', '2026-03-06', 'North NJ', '', '#', '2026-04-29T21:18:11.111Z', 'Jersey City', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (153, 'COUNTRY LINE DANCING', 'Live event in Asbury Park, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-29T21:24:27.012Z', 'Asbury Park', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (154, 'AYA FRIDAYS', 'Live event in Edison, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-29T21:24:27.038Z', 'Edison', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (155, 'FRIDAY NIGHT OUT', 'Live event in Plainfield, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-29T21:24:27.051Z', 'Plainfield', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (156, 'UNDERGROUND FRIDAYS WITH DJ FIORELLA', 'Live event in Somerville, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-29T21:24:27.055Z', 'Somerville', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (157, '90s vs 2000s BASH', 'Live event in East Brunswick, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-29T21:24:27.067Z', 'East Brunswick', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (158, 'SAK PASE AFRO - GHANA INDEPENDENCE DAY', 'Live event in Roselle, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-29T21:24:27.071Z', 'Roselle', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (159, 'THE BIGGIE BRUNCH', 'Live event in Clifton, NJ', '2026-03-06', 'North NJ', '', '#', '2026-04-29T21:24:27.074Z', 'Clifton', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (160, 'JOJOS HAPPY HOUR', 'Live event in Garfield, NJ', '2026-03-06', 'North NJ', '', '#', '2026-04-29T21:24:27.077Z', 'Garfield', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (161, 'COMMUNITY NIGHT: JOURNEYS HOME BY MOONLIGHT', 'Live event in Newark, NJ', '2026-03-06', 'North NJ', '', '#', '2026-04-29T21:24:27.081Z', 'Newark', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (162, 'JAZZY FRIDAYS', 'Live event in Fort Lee, NJ', '2026-03-06', 'North NJ', '', '#', '2026-04-29T21:24:27.085Z', 'Fort Lee', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (163, 'DREAM: A LISTENING & VISUAL EXPERIENCE', 'Live event in Jersey City, NJ', '2026-03-06', 'North NJ', '', '#', '2026-04-29T21:24:27.088Z', 'Jersey City', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (164, 'COUNTRY LINE DANCING', 'Live event in Asbury Park, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-29T21:46:31.192Z', 'Asbury Park', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (165, 'AYA FRIDAYS', 'Live event in Edison, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-29T21:46:31.413Z', 'Edison', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (166, 'FRIDAY NIGHT OUT', 'Live event in Plainfield, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-29T21:46:31.418Z', 'Plainfield', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (167, 'UNDERGROUND FRIDAYS WITH DJ FIORELLA', 'Live event in Somerville, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-29T21:46:31.421Z', 'Somerville', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (168, '90s vs 2000s BASH', 'Live event in East Brunswick, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-29T21:46:31.425Z', 'East Brunswick', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (169, 'SAK PASE AFRO - GHANA INDEPENDENCE DAY', 'Live event in Roselle, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-29T21:46:31.428Z', 'Roselle', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (170, 'THE BIGGIE BRUNCH', 'Live event in Clifton, NJ', '2026-03-06', 'North NJ', '', '#', '2026-04-29T21:46:31.534Z', 'Clifton', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (171, 'JOJOS HAPPY HOUR', 'Live event in Garfield, NJ', '2026-03-06', 'North NJ', '', '#', '2026-04-29T21:46:31.646Z', 'Garfield', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (172, 'COMMUNITY NIGHT: JOURNEYS HOME BY MOONLIGHT', 'Live event in Newark, NJ', '2026-03-06', 'North NJ', '', '#', '2026-04-29T21:46:31.650Z', 'Newark', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (173, 'JAZZY FRIDAYS', 'Live event in Fort Lee, NJ', '2026-03-06', 'North NJ', '', '#', '2026-04-29T21:46:31.653Z', 'Fort Lee', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (174, 'DREAM: A LISTENING & VISUAL EXPERIENCE', 'Live event in Jersey City, NJ', '2026-03-06', 'North NJ', '', '#', '2026-04-29T21:46:31.657Z', 'Jersey City', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (175, 'COUNTRY LINE DANCING', 'Live event in Asbury Park, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-29T21:57:13.282Z', 'Asbury Park', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (176, 'AYA FRIDAYS', 'Live event in Edison, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-29T21:57:13.287Z', 'Edison', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (177, 'FRIDAY NIGHT OUT', 'Live event in Plainfield, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-29T21:57:13.291Z', 'Plainfield', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (178, 'UNDERGROUND FRIDAYS WITH DJ FIORELLA', 'Live event in Somerville, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-29T21:57:13.303Z', 'Somerville', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (179, '90s vs 2000s BASH', 'Live event in East Brunswick, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-29T21:57:13.308Z', 'East Brunswick', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (180, 'SAK PASE AFRO - GHANA INDEPENDENCE DAY', 'Live event in Roselle, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-29T21:57:13.311Z', 'Roselle', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (181, 'THE BIGGIE BRUNCH', 'Live event in Clifton, NJ', '2026-03-06', 'North NJ', '', '#', '2026-04-29T21:57:13.314Z', 'Clifton', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (182, 'JOJOS HAPPY HOUR', 'Live event in Garfield, NJ', '2026-03-06', 'North NJ', '', '#', '2026-04-29T21:57:13.319Z', 'Garfield', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (183, 'COMMUNITY NIGHT: JOURNEYS HOME BY MOONLIGHT', 'Live event in Newark, NJ', '2026-03-06', 'North NJ', '', '#', '2026-04-29T21:57:13.323Z', 'Newark', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (184, 'JAZZY FRIDAYS', 'Live event in Fort Lee, NJ', '2026-03-06', 'North NJ', '', '#', '2026-04-29T21:57:13.326Z', 'Fort Lee', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (185, 'DREAM: A LISTENING & VISUAL EXPERIENCE', 'Live event in Jersey City, NJ', '2026-03-06', 'North NJ', '', '#', '2026-04-29T21:57:13.330Z', 'Jersey City', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (186, 'COUNTRY LINE DANCING', 'Live event in Asbury Park, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-30T01:14:35.348Z', 'Asbury Park', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (187, 'AYA FRIDAYS', 'Live event in Edison, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-30T01:14:35.388Z', 'Edison', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (188, 'FRIDAY NIGHT OUT', 'Live event in Plainfield, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-30T01:14:35.392Z', 'Plainfield', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (189, 'UNDERGROUND FRIDAYS WITH DJ FIORELLA', 'Live event in Somerville, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-30T01:14:35.403Z', 'Somerville', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (190, '90s vs 2000s BASH', 'Live event in East Brunswick, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-30T01:14:35.414Z', 'East Brunswick', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (191, 'SAK PASE AFRO - GHANA INDEPENDENCE DAY', 'Live event in Roselle, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-30T01:14:35.419Z', 'Roselle', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (192, 'THE BIGGIE BRUNCH', 'Live event in Clifton, NJ', '2026-03-06', 'North NJ', '', '#', '2026-04-30T01:14:35.422Z', 'Clifton', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (193, 'JOJOS HAPPY HOUR', 'Live event in Garfield, NJ', '2026-03-06', 'North NJ', '', '#', '2026-04-30T01:14:35.425Z', 'Garfield', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (194, 'COMMUNITY NIGHT: JOURNEYS HOME BY MOONLIGHT', 'Live event in Newark, NJ', '2026-03-06', 'North NJ', '', '#', '2026-04-30T01:14:35.429Z', 'Newark', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (195, 'JAZZY FRIDAYS', 'Live event in Fort Lee, NJ', '2026-03-06', 'North NJ', '', '#', '2026-04-30T01:14:35.432Z', 'Fort Lee', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (196, 'DREAM: A LISTENING & VISUAL EXPERIENCE', 'Live event in Jersey City, NJ', '2026-03-06', 'North NJ', '', '#', '2026-04-30T01:14:35.435Z', 'Jersey City', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (197, 'COUNTRY LINE DANCING', 'Live event in Asbury Park, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-30T12:49:25.791Z', 'Asbury Park', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (198, 'AYA FRIDAYS', 'Live event in Edison, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-30T12:49:25.809Z', 'Edison', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (199, 'FRIDAY NIGHT OUT', 'Live event in Plainfield, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-30T12:49:25.813Z', 'Plainfield', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (200, 'UNDERGROUND FRIDAYS WITH DJ FIORELLA', 'Live event in Somerville, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-30T12:49:25.816Z', 'Somerville', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (201, '90s vs 2000s BASH', 'Live event in East Brunswick, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-30T12:49:25.820Z', 'East Brunswick', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (202, 'SAK PASE AFRO - GHANA INDEPENDENCE DAY', 'Live event in Roselle, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-30T12:49:25.824Z', 'Roselle', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (203, 'THE BIGGIE BRUNCH', 'Live event in Clifton, NJ', '2026-03-06', 'North NJ', '', '#', '2026-04-30T12:49:25.827Z', 'Clifton', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (204, 'JOJOS HAPPY HOUR', 'Live event in Garfield, NJ', '2026-03-06', 'North NJ', '', '#', '2026-04-30T12:49:25.831Z', 'Garfield', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (205, 'COMMUNITY NIGHT: JOURNEYS HOME BY MOONLIGHT', 'Live event in Newark, NJ', '2026-03-06', 'North NJ', '', '#', '2026-04-30T12:49:25.835Z', 'Newark', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (206, 'JAZZY FRIDAYS', 'Live event in Fort Lee, NJ', '2026-03-06', 'North NJ', '', '#', '2026-04-30T12:49:25.838Z', 'Fort Lee', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (207, 'DREAM: A LISTENING & VISUAL EXPERIENCE', 'Live event in Jersey City, NJ', '2026-03-06', 'North NJ', '', '#', '2026-04-30T12:49:25.842Z', 'Jersey City', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (208, 'COUNTRY LINE DANCING', 'Live event in Asbury Park, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-30T18:22:39.308Z', 'Asbury Park', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (209, 'AYA FRIDAYS', 'Live event in Edison, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-30T18:22:39.317Z', 'Edison', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (210, 'FRIDAY NIGHT OUT', 'Live event in Plainfield, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-30T18:22:39.321Z', 'Plainfield', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (211, 'UNDERGROUND FRIDAYS WITH DJ FIORELLA', 'Live event in Somerville, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-30T18:22:39.324Z', 'Somerville', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (212, '90s vs 2000s BASH', 'Live event in East Brunswick, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-30T18:22:39.328Z', 'East Brunswick', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (213, 'SAK PASE AFRO - GHANA INDEPENDENCE DAY', 'Live event in Roselle, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-30T18:22:39.331Z', 'Roselle', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (214, 'THE BIGGIE BRUNCH', 'Live event in Clifton, NJ', '2026-03-06', 'North NJ', '', '#', '2026-04-30T18:22:39.334Z', 'Clifton', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (215, 'JOJOS HAPPY HOUR', 'Live event in Garfield, NJ', '2026-03-06', 'North NJ', '', '#', '2026-04-30T18:22:39.337Z', 'Garfield', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (216, 'COMMUNITY NIGHT: JOURNEYS HOME BY MOONLIGHT', 'Live event in Newark, NJ', '2026-03-06', 'North NJ', '', '#', '2026-04-30T18:22:39.340Z', 'Newark', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (217, 'JAZZY FRIDAYS', 'Live event in Fort Lee, NJ', '2026-03-06', 'North NJ', '', '#', '2026-04-30T18:22:39.343Z', 'Fort Lee', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (218, 'DREAM: A LISTENING & VISUAL EXPERIENCE', 'Live event in Jersey City, NJ', '2026-03-06', 'North NJ', '', '#', '2026-04-30T18:22:39.347Z', 'Jersey City', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (219, 'COUNTRY LINE DANCING', 'Live event in Asbury Park, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-30T21:40:54.697Z', 'Asbury Park', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (220, 'AYA FRIDAYS', 'Live event in Edison, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-30T21:40:54.707Z', 'Edison', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (221, 'FRIDAY NIGHT OUT', 'Live event in Plainfield, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-30T21:40:54.711Z', 'Plainfield', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (222, 'UNDERGROUND FRIDAYS WITH DJ FIORELLA', 'Live event in Somerville, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-30T21:40:54.715Z', 'Somerville', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (223, '90s vs 2000s BASH', 'Live event in East Brunswick, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-30T21:40:54.719Z', 'East Brunswick', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (224, 'SAK PASE AFRO - GHANA INDEPENDENCE DAY', 'Live event in Roselle, NJ', '2026-03-06', 'Central NJ', '', '#', '2026-04-30T21:40:54.722Z', 'Roselle', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (225, 'THE BIGGIE BRUNCH', 'Live event in Clifton, NJ', '2026-03-06', 'North NJ', '', '#', '2026-04-30T21:40:54.725Z', 'Clifton', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (226, 'JOJOS HAPPY HOUR', 'Live event in Garfield, NJ', '2026-03-06', 'North NJ', '', '#', '2026-04-30T21:40:54.727Z', 'Garfield', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (227, 'COMMUNITY NIGHT: JOURNEYS HOME BY MOONLIGHT', 'Live event in Newark, NJ', '2026-03-06', 'North NJ', '', '#', '2026-04-30T21:40:54.730Z', 'Newark', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (228, 'JAZZY FRIDAYS', 'Live event in Fort Lee, NJ', '2026-03-06', 'North NJ', '', '#', '2026-04-30T21:40:54.733Z', 'Fort Lee', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO events (id, title, description, date, region, image_url, ticket_link, created_at, city, event_time, venue, organizer, influencer, genre, instagram_handle) VALUES (229, 'DREAM: A LISTENING & VISUAL EXPERIENCE', 'Live event in Jersey City, NJ', '2026-03-06', 'North NJ', '', '#', '2026-04-30T21:40:54.736Z', 'Jersey City', NULL, NULL, NULL, NULL, NULL, NULL);

-- Table: link_clicks (1 rows)
INSERT INTO link_clicks (id, post_id, url, clicked_at, source_page) VALUES (1, 1, 'https://example.com', '2026-03-18T19:15:47.390Z', NULL);

-- Table: newsletter_subscribers (17 rows)
INSERT INTO newsletter_subscribers (id, name, email, region, created_at, referrer, has_access) VALUES (1, 'test', 'test@example.com', 'All', '2026-03-18T19:15:37.775Z', 'https://google.com', true);
INSERT INTO newsletter_subscribers (id, name, email, region, created_at, referrer, has_access) VALUES (2, 'commenter', 'commenter@example.com', 'All', '2026-03-18T19:21:16.559Z', NULL, true);
INSERT INTO newsletter_subscribers (id, name, email, region, created_at, referrer, has_access) VALUES (3, 'goodsub', 'goodsub@example.com', 'All', '2026-03-18T19:25:15.604Z', NULL, true);
INSERT INTO newsletter_subscribers (id, name, email, region, created_at, referrer, has_access) VALUES (4, 'subscriber5', 'subscriber5@example.com', 'All', '2026-03-18T19:32:16.796Z', NULL, true);
INSERT INTO newsletter_subscribers (id, name, email, region, created_at, referrer, has_access) VALUES (5, 'aagu1999', 'aagu1999@gmail.com', 'All', '2026-03-22T22:59:21.933Z', 'https://3de72ff5-ef09-4644-b273-f7f1a5ea9f61-00-29lbdiuks5vow.worf.replit.dev/__replco/workspace_iframe.html?initialPath=%2F&id=default-start-application', true);
INSERT INTO newsletter_subscribers (id, name, email, region, created_at, referrer, has_access) VALUES (8, 'anniee.xo.17', 'anniee.xo.17@gmail.com', 'All', '2026-04-02T05:02:18.590Z', NULL, true);
INSERT INTO newsletter_subscribers (id, name, email, region, created_at, referrer, has_access) VALUES (9, 'timilehin1108', 'timilehin1108@gmail.com', 'All', '2026-04-02T05:02:22.676Z', NULL, true);
INSERT INTO newsletter_subscribers (id, name, email, region, created_at, referrer, has_access) VALUES (10, 'sostcyr', 'sostcyr@gmail.com', 'All', '2026-04-02T05:02:26.633Z', NULL, true);
INSERT INTO newsletter_subscribers (id, name, email, region, created_at, referrer, has_access) VALUES (11, 'michaelemeam24', 'michaelemeam24@gmail.com', 'All', '2026-04-02T05:02:30.467Z', NULL, true);
INSERT INTO newsletter_subscribers (id, name, email, region, created_at, referrer, has_access) VALUES (12, 'maaterjayy24', 'maaterjayy24@gmail.com', 'All', '2026-04-02T05:02:34.388Z', NULL, true);
INSERT INTO newsletter_subscribers (id, name, email, region, created_at, referrer, has_access) VALUES (13, 'aladyfirst84', 'aladyfirst84@yahoo.com', 'All', '2026-04-02T05:02:38.213Z', NULL, true);
INSERT INTO newsletter_subscribers (id, name, email, region, created_at, referrer, has_access) VALUES (14, 'tosin3oladipo', 'tosin3oladipo@gmail.com', 'All', '2026-04-02T05:02:42.123Z', NULL, true);
INSERT INTO newsletter_subscribers (id, name, email, region, created_at, referrer, has_access) VALUES (15, 'uniteeclubb', 'uniteeclubb@gmail.com', 'All', '2026-04-02T05:02:46.037Z', NULL, true);
INSERT INTO newsletter_subscribers (id, name, email, region, created_at, referrer, has_access) VALUES (16, 'brylax93', 'brylax93@gmail.com', 'All', '2026-04-02T05:02:50.077Z', NULL, true);
INSERT INTO newsletter_subscribers (id, name, email, region, created_at, referrer, has_access) VALUES (17, 'jax.akinde', 'jax.akinde@gmail.com', 'All', '2026-04-02T05:02:53.949Z', NULL, true);
INSERT INTO newsletter_subscribers (id, name, email, region, created_at, referrer, has_access) VALUES (18, 'Pottery N'' Wellness', 'centralgroupevents@gmail.com', 'Central NJ', '2026-04-25T01:28:16.721Z', NULL, true);
INSERT INTO newsletter_subscribers (id, name, email, region, created_at, referrer, has_access) VALUES (20, '', 'test-1777497339210@example.com', NULL, '2026-04-29T21:15:47.471Z', NULL, true);

-- Table: post_versions (1 rows)
INSERT INTO post_versions (id, post_id, title, content, saved_at, saved_by) VALUES (1, 1, 'Test Post', '<p>Hello world</p>', '2026-03-18T19:32:17.820Z', 1);

-- Table: post_views (10 rows)
INSERT INTO post_views (id, post_id, viewed_at) VALUES (1, 1, '2026-03-18T19:15:47.470Z');
INSERT INTO post_views (id, post_id, viewed_at) VALUES (2, 1, '2026-03-18T19:15:54.155Z');
INSERT INTO post_views (id, post_id, viewed_at) VALUES (3, 1, '2026-03-18T19:25:15.559Z');
INSERT INTO post_views (id, post_id, viewed_at) VALUES (4, 1, '2026-03-18T19:29:03.677Z');
INSERT INTO post_views (id, post_id, viewed_at) VALUES (5, 2, '2026-03-18T19:32:17.730Z');
INSERT INTO post_views (id, post_id, viewed_at) VALUES (6, 2, '2026-03-18T19:32:17.773Z');
INSERT INTO post_views (id, post_id, viewed_at) VALUES (7, 2, '2026-03-24T08:51:05.770Z');
INSERT INTO post_views (id, post_id, viewed_at) VALUES (8, 2, '2026-03-30T22:55:28.754Z');
INSERT INTO post_views (id, post_id, viewed_at) VALUES (9, 2, '2026-04-21T00:37:40.846Z');
INSERT INTO post_views (id, post_id, viewed_at) VALUES (10, 2, '2026-04-21T00:38:36.668Z');

-- Table: promotion_bookings (5 rows)
INSERT INTO promotion_bookings (id, venue_name, contact_name, phone, email, event_date, region, event_type, budget_range, instagram_handle, ready_to_move_forward, created_at, mode, event_name, event_time, city, event_type_other, status, admin_notes) VALUES (1, 'Test Venue NJ', 'Test Contact', '5551234567', 'testbooking@example.com', '2026-08-15', 'Central NJ', 'Weekly Night', '$501+', '', NULL, '2026-02-26T03:30:01.036Z', NULL, NULL, NULL, NULL, NULL, 'New', NULL);
INSERT INTO promotion_bookings (id, venue_name, contact_name, phone, email, event_date, region, event_type, budget_range, instagram_handle, ready_to_move_forward, created_at, mode, event_name, event_time, city, event_type_other, status, admin_notes) VALUES (2, 'The Palace', '', '', 'test@example.com', '2026-06-15', 'North NJ', 'Party', '', '', NULL, '2026-03-10T20:02:44.134Z', 'Standard', 'Birthday Bash NJ', '20:00', 'Newark', '', 'New', NULL);
INSERT INTO promotion_bookings (id, venue_name, contact_name, phone, email, event_date, region, event_type, budget_range, instagram_handle, ready_to_move_forward, created_at, mode, event_name, event_time, city, event_type_other, status, admin_notes) VALUES (3, 'Clark park', 'cent b', '3154605159', 'abrahimkenneh@gmail.com', '2026-10-09', 'Central NJ', 'Networking Event', '$150', 'centralgroupevents', NULL, '2026-04-20T22:57:44.114Z', 'Growth', 'Central', '22:00', 'newark', NULL, 'New', NULL);
INSERT INTO promotion_bookings (id, venue_name, contact_name, phone, email, event_date, region, event_type, budget_range, instagram_handle, ready_to_move_forward, created_at, mode, event_name, event_time, city, event_type_other, status, admin_notes) VALUES (4, 'Venue', 'Contact', NULL, 'aagu1999@gmail.com', '2027-01-01', 'Central NJ', 'Other', '$70', 'centralgroupevents', NULL, '2026-04-21T00:14:33.173Z', 'Starter', 'Event Name Pussy', '21:08', 'City', 'Tough', 'New', NULL);
INSERT INTO promotion_bookings (id, venue_name, contact_name, phone, email, event_date, region, event_type, budget_range, instagram_handle, ready_to_move_forward, created_at, mode, event_name, event_time, city, event_type_other, status, admin_notes) VALUES (5, 'central', 'cent b', '3154605159', 'centralgroupevents@gmail.com', '2026-09-04', 'South NJ', 'Comedy Show', '$70', 'centralgroupevents', NULL, '2026-04-21T00:22:52.799Z', 'Starter', 'Central', '17:00', 'newark', NULL, 'New', NULL);

-- ── RESET SEQUENCES ─────────────────────────────────────────────────────

SELECT setval('admin_users_id_seq', 3);
SELECT setval('posts_id_seq', 5);
SELECT setval('comments_id_seq', 2);
SELECT setval('events_id_seq', 230);
SELECT setval('link_clicks_id_seq', 2);
SELECT setval('newsletter_subscribers_id_seq', 21);
SELECT setval('post_versions_id_seq', 2);
SELECT setval('post_views_id_seq', 11);
SELECT setval('promotion_bookings_id_seq', 6);
